#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Write MODELS.md from the registry, so the published list always matches the app.

uv run python scripts/gen_models_md.py [--check]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from irisecho_core.registry import load

ROOT = Path(__file__).resolve().parents[1]
KIND = {
    "image": "Images",
    "edit": "Edits",
    "upscale": "Upscaling",
    "video": "Video",
    "video-upscale": "Video upscaling (API and command line only)",
    "voice": "Voice",
    "clone": "Voice cloning",
    "music": "Music",
    "sfx": "Sound effects",
    "prompt": "Helpers",
}


def size(n: int) -> str:
    gb = n / 2**30
    return f"{gb:.1f} GB" if gb >= 1 else f"{n / 2**20:.0f} MB"


def render() -> str:
    reg = load()
    lines = [
        "# Models",
        "",
        "<!-- Generated by scripts/gen_models_md.py from the registry. Do not edit. -->",
        "",
        "IrisEcho never redistributes model weights. Each file is downloaded from its",
        "publisher's repository, pinned to a commit and checked against a recorded hash,",
        "when you choose to use it. The publisher's license governs your use of the model",
        "and, in some cases, of what it makes.",
        "",
        "Sizes are for an NVIDIA RTX 20/30/40 card (int4 builds); shared files such as text",
        "encoders are counted once per model but downloaded once overall.",
        "",
    ]
    for kind, title in KIND.items():
        models = [m for m in reg.models.values() if m.kind == kind]
        if not models:
            continue
        lines += [
            f"## {title}",
            "",
            "| Model | What it is for | License | Commercial use | Size | Source |",
            "|---|---|---|---|---|---|",
        ]
        for m in models:
            lic = reg.licenses[m.license]
            if lic.condition:
                commercial = lic.condition
            else:
                commercial = "Yes" if lic.commercial else "**No**"
            if lic.gated:
                commercial += " (sign-in required)"
            variant = next(
                (v for v in m.variants if v.when.get("quant", "int4") == "int4"), m.variants[0]
            )
            files = reg.expand(variant.files)
            repos = sorted({f.repo for f in files})
            src = ", ".join(f"[{r}](https://huggingface.co/{r})" for r in repos)
            lines.append(
                f"| {m.name} | {m.summary} | [{lic.name}]({lic.url}) | {commercial} | "
                f"{size(sum(f.size for f in files))} | {src} |"
            )
        lines.append("")
    lines += [
        "## Notes",
        "",
        "- Non-commercial and gated models are opt-in: IrisEcho shows the license and asks",
        "  you to accept it before downloading anything.",
        "- Chatterbox output carries Resemble AI's inaudible Perth watermark. IrisEcho",
        "  keeps it. Only clone voices you have permission to use.",
        "- Stable Audio 3's text encoder is also covered by Google's Gemma Terms of Use.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    target = ROOT / "MODELS.md"
    if args.check:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            print("MODELS.md is out of date; run scripts/gen_models_md.py", file=sys.stderr)
            return 1
        return 0
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
